# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node/rpc/node_user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18node/rpc/node_user.proto\x12\x08NODEUSER\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1b\n\nLoginReply\x12\r\n\x05token\x18\x01 \x01(\t2A\n\x08NodeUser\x12\x35\n\x05Login\x12\x16.NODEUSER.LoginRequest\x1a\x14.NODEUSER.LoginReplyb\x06proto3')



_LOGINREQUEST = DESCRIPTOR.message_types_by_name['LoginRequest']
_LOGINREPLY = DESCRIPTOR.message_types_by_name['LoginReply']
LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'node.rpc.node_user_pb2'
  # @@protoc_insertion_point(class_scope:NODEUSER.LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LoginReply = _reflection.GeneratedProtocolMessageType('LoginReply', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREPLY,
  '__module__' : 'node.rpc.node_user_pb2'
  # @@protoc_insertion_point(class_scope:NODEUSER.LoginReply)
  })
_sym_db.RegisterMessage(LoginReply)

_NODEUSER = DESCRIPTOR.services_by_name['NodeUser']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINREQUEST._serialized_start=38
  _LOGINREQUEST._serialized_end=88
  _LOGINREPLY._serialized_start=90
  _LOGINREPLY._serialized_end=117
  _NODEUSER._serialized_start=119
  _NODEUSER._serialized_end=184
# @@protoc_insertion_point(module_scope)
