# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node/p2p.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from node import api_pb2 as node_dot_api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enode/p2p.proto\x12\x03P2P\x1a\x0enode/api.proto\"6\n\x0eResponseHeader\x12\x11\n\tsignature\x18\x01 \x01(\x0c\x12\x11\n\tpublicKey\x18\x05 \x01(\x0c\"\xe7\x01\n\x0cResponseBody\x12#\n\rsignatureType\x18\x01 \x01(\x0e\x32\x0c.API.SigType\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12,\n\x07success\x18\x03 \x01(\x0b\x32\x19.P2P.ResponseBody.SuccessH\x00\x12\x1f\n\x07\x66\x61ilure\x18\x04 \x01(\x0e\x32\x0c.P2P.FailureH\x00\x12&\n\x04pong\x18\x05 \x01(\x0b\x32\x16.P2P.ResponseBody.PongH\x00\x1a\t\n\x07Success\x1a\x15\n\x04Pong\x12\r\n\x05peers\x18\x01 \x03(\x0c\x42\x06\n\x04\x64\x61ta\"5\n\rRequestHeader\x12\x11\n\tsignature\x18\x01 \x01(\x0c\x12\x11\n\tpublicKey\x18\x05 \x01(\x0c\"\xee\x03\n\x0bRequestBody\x12#\n\rsignatureType\x18\x01 \x01(\x0e\x32\x0c.API.SigType\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12%\n\x04ping\x18\x04 \x01(\x0b\x32\x15.P2P.RequestBody.PingH\x00\x12+\n\x07\x66orward\x18\x05 \x01(\x0b\x32\x18.P2P.RequestBody.ForwardH\x00\x12\x35\n\x0cvoteProposal\x18\x06 \x01(\x0b\x32\x1d.P2P.RequestBody.VoteProposalH\x00\x12/\n\tfinalVote\x18\x07 \x01(\x0b\x32\x1a.P2P.RequestBody.FinalVoteH\x00\x1aW\n\x07\x46orward\x12)\n\rrequestHeader\x18\x01 \x01(\x0b\x32\x12.P2P.RequestHeader\x12!\n\x07request\x18\x02 \x01(\x0b\x32\x10.P2P.RequestBody\x1a:\n\x0cVoteProposal\x12\x1c\n\x05\x62lock\x18\x01 \x01(\x0b\x32\r.API.RawBlock\x12\x0c\n\x04vote\x18\x02 \x01(\x04\x1a\x37\n\tFinalVote\x12\x1c\n\x05\x62lock\x18\x01 \x01(\x0b\x32\r.API.RawBlock\x12\x0c\n\x04vote\x18\x02 \x01(\x04\x1a\x15\n\x04Ping\x12\r\n\x05peers\x18\x01 \x03(\x0c\x42\x06\n\x04\x64\x61ta*H\n\x07\x46\x61ilure\x12\x14\n\x10MalformedRequest\x10\x00\x12\x14\n\x10InvalidSignature\x10\x01\x12\x11\n\rInternalError\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node.p2p_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FAILURE._serialized_start=881
  _FAILURE._serialized_end=953
  _RESPONSEHEADER._serialized_start=39
  _RESPONSEHEADER._serialized_end=93
  _RESPONSEBODY._serialized_start=96
  _RESPONSEBODY._serialized_end=327
  _RESPONSEBODY_SUCCESS._serialized_start=287
  _RESPONSEBODY_SUCCESS._serialized_end=296
  _RESPONSEBODY_PONG._serialized_start=298
  _RESPONSEBODY_PONG._serialized_end=319
  _REQUESTHEADER._serialized_start=329
  _REQUESTHEADER._serialized_end=382
  _REQUESTBODY._serialized_start=385
  _REQUESTBODY._serialized_end=879
  _REQUESTBODY_FORWARD._serialized_start=644
  _REQUESTBODY_FORWARD._serialized_end=731
  _REQUESTBODY_VOTEPROPOSAL._serialized_start=733
  _REQUESTBODY_VOTEPROPOSAL._serialized_end=791
  _REQUESTBODY_FINALVOTE._serialized_start=793
  _REQUESTBODY_FINALVOTE._serialized_end=848
  _REQUESTBODY_PING._serialized_start=850
  _REQUESTBODY_PING._serialized_end=871
# @@protoc_insertion_point(module_scope)
